boss-bar-messages:
  - "&7Coming soon> &b&oEven §b§l§oMORE §b§ospells!"
  - "&7Coming soon> &b&oAlpha testing"
  - "&7Newest feature> &b&oMelofors spell"

rules:
  - "Use proper etiquette"
  - "Be friendly towards your other players"

players:
  uuid:
    lastKnownName: Username
    sessionsPlayed: 0