ping-message: '&4&lGodrics&6&lMC &7Test server'

boss-bar-messages:
  - "%pColorComing soon> %sColorMore spells!"

rules:
  - "Use proper etiquette"
  - "Be friendly towards your other players"

staffRanks:
  - developer
  - leaddeveloper
  - architect
  - leadarchitect
  - prefect
  - headboy
  - headgirl
  - professor
  - minister
  - headauror
  - headofhouse

players:
  uuid:
    lastKnownName: Username
    sessionsPlayed: 0

mailbox:
  uuid:
    packages:
      uuid:
        message: '&6Hey!'
        items:

houseSettings:
  gryffindor:
    points: 0
    primaryColor: 4
    secondaryColor: e
  slytherin:
    points: 0
    primaryColor: 2
    secondaryColor: 7
  ravenclaw:
    points: 0
    primaryColor: 9
    secondaryColor: 7
  hufflepuff:
    points: 0
    primaryColor: e
    secondaryColor: 7